var noOfButtons = 25;
var score = 0;
var split_word = [];
var temp_word="";

function assign()
{
	var btn_val=[];
	var equation_string="";
	var final_alphabet=[];		//array of letters to be displayed on the buttons
	var select_word,j;
	var temp_alphabet=[];
	
	reset();
	document.getElementById("name").innerHTML = gen.name;
	document.getElementById("NextQuestion").innerHTML = gen.NextQuestion;
	document.getElementById("CancelSelected").innerHTML = gen.CancelSelected;
	document.getElementById("SubmitChoice").innerHTML = gen.SubmitChoice;
	document.getElementById("SkipQuestion").innerHTML = gen.SkipQuestion;
	document.getElementById("ScoreText").innerHTML = gen.ScoreText;
	document.getElementById("answerbox").style.display = "None";
	document.getElementById("score_val").innerHTML = String(score);
	
	select_word=Math.ceil(Math.random()*(dictionary.length-1));
	temp_word=String(dictionary[select_word].word); //dictionary is a json array which some meaning full words are stored of which equation are to be made of.
	split_word=temp_word.split(" ");
	/*Copies all letters from the database into a local array*/
	for (var i = 0; i <alphabet.length; i++) 
	{
		temp_alphabet[i]=alphabet[i];
	}
	/*Includes the answer in the array of letters to be displayed*/
	for(var j=0;j<split_word.length;j++)
	{
		final_alphabet[final_alphabet.length]=split_word[j];
	}
	/*Includes the remaining number of letters in the array*/
	while(final_alphabet.length<=noOfButtons)
	{
		var j;
		var temp;
		while(1)
		{
			temp=Math.floor(Math.random()*(temp_alphabet.length));
			for(j=0;j<final_alphabet.length;j++)
			{
				if(temp_alphabet[temp]==final_alphabet[j])
					break;
			}
			if(j==final_alphabet.length)
				break;
		}
		final_alphabet[final_alphabet.length]=temp_alphabet.splice(temp,1);
	}
	/*Assigns randomly the letters to be displayed on the buttons*/
	for(var k=0;k<noOfButtons;k++)
	{
		var temp=Math.floor(Math.random()*(final_alphabet.length-1));
		document.getElementById("name"+String(k+1)).innerHTML=final_alphabet.splice(temp,1);
	}
	/* The following loop assigns each button a random value between 1 to 99 
	which does not get repeated*/
	for(var i=0;i<noOfButtons;i++)			
	{
		while(1)
		{
			var temp =Math.ceil(Math.random()*99); //99 is multiplied to keep the random value generated in between 1 to 99 (i.e. two digit random value).
			for(j=0;j<btn_val.length;j++)		//this loop checks whether the current random value is assigned previously.
			{
				if(temp==btn_val[j])
					break;
			}
			if(j==btn_val.length)
				break;
		}
		btn_val[j]=temp;
		if(temp<10)			//if assigned value is less than 10 then it will have a '0' in front of the value i.e display '09' instead of '9'.
			document.getElementById("temp"+String(i+1)).innerHTML=String(0)+String(temp);
		else
			document.getElementById("temp"+String(i+1)).innerHTML= String(temp);
	}

	/*this loop is used to display the equations generated by the equation() function for the particular word selected.*/
	for(var i=0;i<split_word.length;i++)
	{
		for(var j=0;j<noOfButtons;j++)
		{
			
			if(split_word[i]==document.getElementById("name"+String(j+1)).innerHTML)
			{
				equation_string = equation_string + equation(parseInt(document.getElementById("temp"+String(j+1)).innerHTML)) + " ͏ ";
				break;
			}
		}
	}
	document.getElementById("equations").innerHTML=String(equation_string);
}
/*To reset the correct answer and entered answer*/
function reset()
{
	document.getElementById("enteredText").value="";
	document.getElementById("ans").innerHTML="";
}
onload=function scorerefresh()
{
	score=0;
}
/*checks whether the entered answer is correct and displays appropriate messages*/
function check()
{
	temp_word = temp_word.replace(/ /g,"");
	
	if(temp_word==document.getElementById("enteredText").value)
	{
		document.getElementById("greet").innerHTML=gen.greeting1;
		document.getElementById("ans").innerHTML=gen.message1;
		score++;
	}
	else
	{
		document.getElementById("greet").innerHTML=gen.greeting2;
		document.getElementById("ans").innerHTML=gen.message2 + temp_word;
	}
	document.getElementById("answerbox").style.display = "block";
	document.getElementById("score_val").innerHTML = String(score);
}

/*This function generates equations of different types:
x*y+z
x*y-z
x/y+z
x/y-z
*/
function equation(num)
{
	var quotient,remainder,temp,q;
	var multiplicand;
	var decision=Math.ceil(Math.random()*9);	//decide whether equation is of multiplication or division.
	var offset=Math.ceil(Math.random()*9);		//find which value should be added or subtracted.
	var posneg=Math.ceil(Math.random()*9);		//decide whether offset should be added or subtracted.
	var select_word=Math.ceil(Math.random()*9);		//decide which value should divide or multiply.
	temp=num;
	if(decision>5)			//for equation of multiplication form
	{
		quotient=Math.floor(num/select_word);		//number to which select_word should be multiplied
		remainder=num%select_word;					//offset
		if(posneg>5)
		{
			quotient+=1;
			remainder=select_word-remainder;
			if(remainder==0)
				q=String(quotient + "*" + select_word);	
			else
				q=String("(" + quotient + "*" + select_word +")" + "-" + remainder);
		}
		else
		{
			if(remainder==0)				
				q=String(quotient + "*" + select_word);
			else
				q=String("(" + quotient + "*" + select_word + ")" + "+" + remainder);
		}
	}
	else					//for equation of division form
	{
		if(posneg>5)
		{
			multiplicand=select_word*(num-offset);
			q=String("(" + multiplicand + "÷" + select_word +")"+ "+" + offset);
		}
		else
		{
			multiplicand=select_word*(num+offset);
			q=String("(" + multiplicand + "÷" + select_word +")"+ "-" + offset);	
		}
	}
	return q;
}
/* This function appends the alphabet on the button clicked in the answer textbox*/
function puttext(identity)
{
	var btn_alphabet=String(identity.innerHTML);
	btn_alphabet=btn_alphabet.split(/>|</);
	document.getElementById("enteredText").value += String(btn_alphabet[2]);
}
